# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d47dcb3d19e639a86dff9b3bd869fb18296ab2e3ec7df3652b616c8184a3df4bbbc0aff140b33ed5e9b60e3b8d192bdf8b0d77c161619d0af0a61caaa09807

test:
  secret_key_base: 22e624b5638869806372df0f82b0f8a326fb0364220f0fb74be64f53e0d32f28d2eb03b7a491bf72d72b977d2139dba099f1fc249840aec6e417a82b74c6468e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
